INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (1, 'Chodec věnoval pozornost', 'Díval se na cestu před sebou', '2010-09-07', 1, 1);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (2, 'Obec porušila standard řádné péče', 'Neměla zpracovaný plán údržby', '2010-09-07', 1, 1);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (3, 'Porušil povinnost prevence', 'Neměl vhodnou obuv.', '2010-09-07', 1, 1);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (4, 'Byla výluka z plnění plánu údržby', 'čas pádu nastal v době, kdy údržba nemohla zajistit odpovídající stav dle plánu údržby v přiměřené lhůtě.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (5, 'Byla výstraha,', 'ČHMÚ varoval v den pádu o riziku námrazy.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (6, 'Chodec byl fyzicky i psychicky způsobilý,', 'se jedná o běžného čtyřicátníka, který šel ráno do práce.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (7, 'Chodec věnoval pozornost', 'se díval před sebe pod nohy.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (8, 'Obec měla zpracovaný plán údržby', 'protože byl schválen veřejnou vyhláškou.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (9, 'Obuv byla vhodná', 'podrážka měla hrubý vzorek', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (10, 'Stav chodníku byl vyhovující', 'v zimě bývá obvykle sníh a led všude.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (11, 'Stav chodníku nebyl vyhovující', 'bylo náledí.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (12, 'Zvolená trasa byla nebezpečná', 'obsahovala změnu terénu.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (13, 'Zvolená trasa byla riziková', 'trasa obsahovala místo vedoucí kolem kontejnerů bez pokrytí úklidem a s viditelnými zmrazky.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (14, 'Zvolená trasa byla známá', 'tudy chodec chodil do práce.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (15, 'Zvolená trasa nebyla bezpečná', 'vedla šikmo z vozovky.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (16, 'Závada byla překvapivá', 'protože neošetřená část byla zjistitelná jen se zvýšeným vizuálním úsilím.', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (17, 'Závada nebyla ojedinělá', 'v danou chvíli byla kluzká celá ulice', '2010-09-07', 1, 2);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (22, 'TEST predicate', 'test premise', null, null, 7);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (23, 'Jsem vysoký', 'měřím 182 cm.', null, null, 8);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (24, 'Jsem vysoký', 'měřím 180 m.', null, null, 9);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (25, 'test predicate', 'test premise', null, null, 10);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (26, 'Berta je vysoká', 'měří 178 cm.', null, null, 11);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (27, 'Nárok je důvodný', 'délka soudního řízení byla nepřiměřená.', null, null, 12);
INSERT INTO public.pets (id, name, premisa, birth_date, type_id, owner_id) VALUES (28, 'Řízeni mělo pro poškozeného význam', 'se jednalo o pracovněprávní věc.', null, null, 12);
